### ISSUE TITLE
Removal of the file header comment in main.py file

### ISSUE THREAD

**Issue by georgemunyoro** [georgemunyoro/skaak#18]

**Comment by EmeraldEntities** [comment]
is this quite literally just removing the header comment? I'm not sure how issues work but I can do this one if that's all you need

**Comment by bidetaggle** [comment]
Yes I think it is only this, sorry I felt like doing the PR straight after I read this issue

**Comment by EmeraldEntities** [comment]
all good, have a good hacktoberfest!

**Comment by bidetaggle** [comment]
Thank you, have a good hacktoberfest too!
