### ISSUE TITLE
Add editor config folders to gitignore

### ISSUE THREAD

**Issue by georgemunyoro** [georgemunyoro/skaak#24]
Editors generally create config files when in projects, `.idea/`, `.vscode/` for example. It wouId be great to have the gitignore cover as many of the popular editors as possible so these files dont get into PRs and repos. So VsCode, Pycharm, Sublime, etc. I was going to do this myself but thought it could be a good first issue for someone.

**Comment by morpheusthewhite** [comment]
I would suggest against it 

https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/

**Comment by georgemunyoro** [comment]
This is a valid point, and while I do in fact have a global .gitignore set up, not everyone does, and having these files ignored on the project level is much more convenient for new contributors who do not have have a global .gitignore

**Comment by habereet** [comment]
I can take this. I wasn't aware of global .gitignores so I can do this and help my own repos by cleaning them up a bit.

**Comment by JoelLau** [comment]
hi, can I work on this as part of Hacktoberfest?

**Comment by morpheusthewhite** [comment]
> This is a valid point, and while I do in fact have a global .gitignore set up, not everyone does, and having these files ignored on the project level is much more convenient for new contributors who do not have have a global .gitignore

This is not the best option for me, as you read. I also think new contributors (to external repositories I mean) are often aware of what must be ignored and not pushed, and eventually I'd prefer fixing the PR than keeping this redundant entries in all the .gitignore

**Comment by dakshayahuja** [comment]
Hey @georgemunyoro,
I would like to work on this issue.
Please assign it to me.
