### ISSUE TITLE
Remove redundant methods and unused code

### ISSUE THREAD

**Issue by georgemunyoro** [georgemunyoro/skaak#3]

**Comment by Apoorve73** [comment]
I can improve that! :+1:

**Comment by georgemunyoro** [comment]
Sure, np

**Comment by Apoorve73** [comment]
Code is not running and facing many errors. Can you first check that? I can continue till then.

**Comment by pecey** [comment]
At present the code doesn't seem to do anything. I fixed all the bugs, but I can't see any calls happening to any of the functions other than init. Am I missing something?

**Comment by georgemunyoro** [comment]
Initially this was meant to be the an engine, but I never got around to building a proper game loop, allowing a user to play the engine. I would simply run it in interactive mode and mess around with it that way. Now that this is a library, there is no need for such a loop. Rather it is simply imported and users can use it to build their own chess programs.

**Comment by pecey** [comment]
I think it makes even more sense to have tests in that case. I have already opened an issue regarding that.
